name: Auto Approve Dependency PRs

on: pull_request_target

jobs:
  check-rate-limit:
    runs-on: ubuntu-latest
    outputs:
      should_approve: ${{ steps.check-limit.outputs.should_approve }}
    if: contains(github.event.pull_request.title, 'Update dependency licenses')
    steps:
      - name: Check approval rate limit
        id: check-limit
        run: |
          # Get recent workflow runs in the last hour
          RECENT_APPROVALS=$(gh api \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/actions/runs?event=pull_request_target&status=completed&created=`date -u -d '1 hour ago' '+%Y-%m-%dT%H:%M:%SZ'`" \
            --jq '.workflow_runs | map(select(.name == "Auto Approve Dependency PRs" and .conclusion == "success")) | length')
          
          echo "Found $RECENT_APPROVALS auto-approvals in the last hour"
          
          # Set limit (e.g., 3 per hour)
          if [ "$RECENT_APPROVALS" -lt 3 ]; then
            echo "should_approve=true" >> $GITHUB_OUTPUT
          else
            echo "should_approve=false" >> $GITHUB_OUTPUT
            echo "Rate limit reached: $RECENT_APPROVALS approvals in the last hour"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-approve:
    needs: check-rate-limit
    if: needs.check-rate-limit.outputs.should_approve == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "Auto-approved dependency update (within hourly rate limit)"