name: Build ARM64 Binaries for BirdNET-Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-arm64:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        check-latest: true

    - name: Install ARM64 dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Download & Set up TensorFlow Lite C library for ARM64
      run: |
        wget https://github.com/tphakala/tflite_c/releases/download/v2.14.0/tflite_c_v2.14.0_linux_arm64.tar.gz
        mkdir tflite_c
        tar -xzf tflite_c_v2.14.0_linux_arm64.tar.gz -C tflite_c
        sudo cp tflite_c/libtensorflowlite_c.so /usr/local/lib/
        sudo ldconfig

    - name: Clone TensorFlow repository
      run: |
        mkdir -p ~/src
        git clone --branch v2.14.0 --depth 1 https://github.com/tensorflow/tensorflow.git ~/src/tensorflow

    - name: Build BirdNET-Go for ARM64
      run: |
        make linux_arm64

    - name: Upload ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: birdnet-go_linux_arm64
        path: |
          bin/birdnet-go_arm64
          tflite_c/libtensorflowlite_c.so
