name: Deploy Image to GHCR

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4.1.1

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Generate downcase repository name'
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: 'Build Inventory Image'
      run: |
        docker build . --tag ghcr.io/${REPO}:latest
        docker push ghcr.io/${REPO}:latest
