name: golangci-test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    uses: ./.github/workflows/golangci-lint.yml

  unit-tests:
    needs: golangci
    runs-on: ubuntu-24.04
    services:
      mosquitto:
        image: eclipse-mosquitto:1.6
        ports:
          - 1883:1883
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go version

      - name: Install dependencies
        run: make check-tensorflow

      - name: Download tflite_c
        run: make download-tflite-linux-amd64

      - name: Set environment variables for CGO
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I $HOME/src/tensorflow" >> $GITHUB_ENV

      - name: Set up gotestfmt
        run: go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

      - name: Wait for Mosquitto
        run: |
          echo "Waiting for Mosquitto to be ready..."
          for i in {1..30}; do
            if nc -zv localhost 1883 2>/dev/null; then
              echo "Mosquitto is ready!"
              break
            fi
            echo "Attempt $i: Mosquitto not ready yet, waiting..."
            sleep 1
          done
          # Final check
          nc -zv localhost 1883 || { echo "Mosquitto failed to start"; exit 1; }

      - name: Run unit tests
        env:
          CI: true
          MQTT_TEST_BROKER: tcp://localhost:1883
        run: |
          set -euo pipefail
          go test -json -v -timeout 60s ./... 2>&1 | tee /tmp/gotest.log | gotestfmt -ci github

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
