name: BirdNET-Go Nightly Build

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Optional: allow manual trigger
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build binaries
      uses: tphakala/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.22.1.linux-amd64.tar.gz"
        md5sum: false
        sha256sum: false
        compress_assets: auto
        build_command: make ${{ matrix.goos }}_${{ matrix.goarch }}
        extra_files: libtensorflowlite_c.so
        # Instead of attaching to a release, artifacts will be uploaded
        project_path: "."
        binary_name: "birdnet-go"

  docker-nightly:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate downcase repository name
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: ghcr.io/${{ env.REPO }}
        tags: |
          type=raw,value=nightly
          type=raw,value=nightly-{{date 'YYYYMMDD'}}

    - name: Tag docker image with nightly version
      run: |
        docker buildx imagetools create -t ghcr.io/${{ env.REPO }}:nightly ghcr.io/${{ env.REPO }}:${{ github.sha }}
        docker buildx imagetools create -t ghcr.io/${{ env.REPO }}:nightly-$(date +%Y%m%d) ghcr.io/${{ env.REPO }}:${{ github.sha }} 