name: BirdNET-Go Release Build

on:
  release:
    types: [created, edited]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: ${{ !contains(github.ref, 'nightly') }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Build and attach to Release
      uses: tphakala/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.23.4.linux-amd64.tar.gz"
        md5sum: false
        sha256sum: false
        compress_assets: auto
        build_command: make ${{ matrix.goos }}_${{ matrix.goarch }}
        extra_files: libtensorflowlite_c.so

  docker-tagging:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate downcase repository name
      run: |
        echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.REPO }}
        tags: |
          type=semver,pattern={{version}}

    - name: Tag docker image with release version
      run: |
        docker buildx imagetools create -t ghcr.io/${{ env.REPO }}:${{ steps.meta.outputs.version }} ghcr.io/${{ env.REPO }}:${{ github.sha }}
        docker buildx imagetools create -t ghcr.io/${{ env.REPO }}:latest ghcr.io/${{ env.REPO }}:${{ github.sha }}
