name: BirdNET-Go Release Build

on:
  release:
    types: [created, edited]
  workflow_dispatch:

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    if: ${{ !contains(github.ref, 'nightly') && (github.event_name == 'release' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config gcc-aarch64-linux-gnu gcc-mingw-w64-x86-64

      - name: Build BirdNET-Go
        run: |
          # Build the application
          make ${{ matrix.goos }}_${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1

      - name: Create Release Artifacts
        run: |
          # Create artifacts directory
          mkdir -p artifacts
          
          # Set binary name based on OS
          BINARY_NAME=birdnet-go
          if [ "${{ matrix.goos }}" = "windows" ]; then
            BINARY_NAME=birdnet-go.exe
          fi
          
          # Copy binary
          cp bin/$BINARY_NAME artifacts/
          
          # Copy required library files based on OS and architecture
          if [ "${{ matrix.goos }}" = "linux" ]; then
            if [ "${{ matrix.goarch }}" = "amd64" ]; then
              cp /usr/lib/libtensorflowlite_c.so artifacts/
            elif [ "${{ matrix.goarch }}" = "arm64" ]; then
              cp /usr/aarch64-linux-gnu/lib/libtensorflowlite_c.so artifacts/
            fi
          elif [ "${{ matrix.goos }}" = "windows" ]; then
            cp /usr/x86_64-w64-mingw32/lib/tensorflowlite_c.dll artifacts/
          fi
          
          # Create tarball
          cd artifacts
          tar czf ../birdnet-go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz *

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: birdnet-go-${{ matrix.goos }}-${{ matrix.goarch }}
          path: birdnet-go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: birdnet-go-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    if: ${{ !contains(github.ref, 'nightly') && (github.event_name == 'release' || github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate downcase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest      

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
            ghcr.io/${{ env.REPO }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          build-args: |
            VERSION=${{ github.ref_name }}
